### ISSUE TITLE
Feature: Integration

### ISSUE THREAD

**Issue by owenversteeg** [hausen/math.diff.js#2]
It's been a while since I took a calculus course, so I'm not sure how doable this is, but would it be possible to do integration as well?

Thanks for your work!

**Comment by hausen** [comment]
Short answer: that would be really hard to program. One would have to implement an almost complete CAS (Computer Algebra System).

Long answer: given an expression tree, the chain rule allows us to (relatively) easily calculate its derivative. There is no such rule for anti-derivatives, so you would have to implement different rules for polynomials, rational functions, trigonometric substitutions, and so on. And you would also need to determine when to apply such rules. As an example, try solving this simpler problem: given an expression tree, determine whether it describes a polynomial.

So, sorry, that would be way outside the scope of this project.

**Comment by owenversteeg** [comment]
No problem, and thanks for the background info!
